#!/usr/bin/env bash

#
# This script optimizes the original veekun/pokedex CSV data structure
# by changing some of the CSV structures
# so the databases importing the data directly will have better performance.
#


# Path from where this script is called
__PATH__=`readlink -f ./`

# CD to root path
cd ${__PATH__}

mkdir -p tmp
mkdir -p data

echo "Cleaning up previously generated CSV files and SQLite databases..."
rm -rf data/csv tmp/csv
rm -rf data/*.sqlite tmp/*.sqlite

./scripts/update-sources || exit 1

# Imports all original CSV files into a temporary SQLite DB
php scripts/db_import.php --tmp || exit 1

sleep 2 # give the computer a break

# Optimizes DB structure and applies fixtures
php scripts/db_migrate.php || exit 1

sleep 2 # give the computer a break

# Exports the database into CSV files
php scripts/db_export.php || exit 1

# Imports all migrated CSV files into a new SQLite DB
php scripts/db_import.php || exit 1

echo "Your Pokémon data is ready to be used!"
echo "You will find all files under the 'data' directory."