#!/usr/bin/env bash

# Path from where this script is called
__PATH__=`readlink -f ./`

echo "Reloading CSV data from latest veekun/pokedex master..."

# CD to root path
cd ${__PATH__}

# Recreate tmp dir if does not exist
mkdir -p tmp

# Delete CSV folders and DBs
rm -rf csv
cd tmp
rm -rf csv *.sqlite

# Clone original data source from Veekun and move files
if [ -d "veekun-pokedex/.git" ]; then
    cd veekun-pokedex
    git checkout master && git reset --hard && git pull -f || exit 1
    cd ..
else
    rm -rf veekun-pokedex # in case it exists, but it's not a git repo.
    git clone https://github.com/veekun/pokedex.git veekun-pokedex || exit 1
fi

cp -R veekun-pokedex/pokedex/data/csv csv || exit 1
# Remove all Conquest-related data (which does not belong to the main series)
rm -f csv/conquest*.csv csv/conquest.csv || exit 1

cd ..

echo "DONE!"
exit 0